import { neon } from '@neondatabase/serverless';

const connectionString =
  process.env.DATABASE_URL || process.env.DATABASE_POSTGRES_URL;

if (!connectionString) {
  throw new Error('DATABASE_URL is unavailable');
}

const sql = neon(connectionString);

const statements = [
  `CREATE TABLE IF NOT EXISTS orders (
    id TEXT PRIMARY KEY,
    order_number TEXT NOT NULL UNIQUE,
    order_type TEXT NOT NULL,
    table_number TEXT,
    customer_name TEXT,
    customer_phone TEXT,
    delivery_address TEXT,
    latitude TEXT,
    longitude TEXT,
    status TEXT NOT NULL DEFAULT 'new',
    payment_status TEXT NOT NULL DEFAULT 'pending',
    payment_method TEXT,
    notes TEXT,
    subtotal INTEGER NOT NULL,
    tax INTEGER NOT NULL,
    discount INTEGER NOT NULL DEFAULT 0,
    total INTEGER NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id TEXT NOT NULL REFERENCES orders(id),
    menu_item_id INTEGER NOT NULL,
    name TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    unit_price INTEGER NOT NULL,
    line_total INTEGER NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS inventory (
    id TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    category TEXT NOT NULL,
    unit TEXT NOT NULL,
    quantity INTEGER NOT NULL,
    reorder_at INTEGER NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS table_bookings (
    id TEXT PRIMARY KEY,
    booking_number TEXT NOT NULL UNIQUE,
    customer_name TEXT NOT NULL,
    phone TEXT NOT NULL,
    guests INTEGER NOT NULL,
    booking_date TEXT NOT NULL,
    booking_time TEXT NOT NULL,
    table_number TEXT NOT NULL,
    notes TEXT,
    status TEXT NOT NULL DEFAULT 'booked',
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS menu_items (
    id INTEGER PRIMARY KEY,
    name TEXT NOT NULL,
    note TEXT NOT NULL,
    price INTEGER NOT NULL,
    category TEXT NOT NULL,
    veg INTEGER NOT NULL DEFAULT 1,
    photo INTEGER NOT NULL DEFAULT 0,
    photo_url TEXT,
    badge TEXT,
    active INTEGER NOT NULL DEFAULT 1,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS site_settings (
    key TEXT PRIMARY KEY,
    value TEXT NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS customer_profiles (
    phone TEXT PRIMARY KEY,
    name TEXT NOT NULL,
    pin_hash TEXT,
    pin_salt TEXT,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS customer_otps (
    phone TEXT PRIMARY KEY,
    code_hash TEXT NOT NULL,
    code_salt TEXT NOT NULL,
    purpose TEXT NOT NULL,
    attempts INTEGER NOT NULL DEFAULT 0,
    expires_at DOUBLE PRECISION NOT NULL,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
  )`,
  `CREATE TABLE IF NOT EXISTS order_feedback (
    order_id TEXT PRIMARY KEY REFERENCES orders(id),
    customer_phone TEXT NOT NULL,
    table_number TEXT,
    food_rating INTEGER NOT NULL,
    service_rating INTEGER NOT NULL,
    notes TEXT,
    created_at DOUBLE PRECISION NOT NULL,
    updated_at DOUBLE PRECISION NOT NULL
  )`,
  'CREATE INDEX IF NOT EXISTS idx_order_items_order_id ON order_items (order_id)',
  'CREATE INDEX IF NOT EXISTS idx_orders_status_created_at ON orders (status, created_at)',
  'CREATE INDEX IF NOT EXISTS idx_orders_payment_status ON orders (payment_status)',
  'CREATE INDEX IF NOT EXISTS idx_orders_customer_phone ON orders (customer_phone, created_at)',
  'CREATE INDEX IF NOT EXISTS idx_bookings_status_date ON table_bookings (status, booking_date)',
  'CREATE INDEX IF NOT EXISTS idx_bookings_table_slot ON table_bookings (table_number, booking_date, booking_time)',
  'CREATE INDEX IF NOT EXISTS idx_bookings_phone ON table_bookings (phone, created_at)',
  'CREATE INDEX IF NOT EXISTS idx_menu_items_active_category ON menu_items (active, category)',
  'CREATE INDEX IF NOT EXISTS idx_order_feedback_customer_phone ON order_feedback (customer_phone, created_at)',
];

for (const statement of statements) {
  await sql.query(statement);
}

const now = Date.now();
const inventory = [
  ['paneer', 'Fresh paneer', 'Dairy', 'kg', 18, 8],
  ['chicken', 'Boneless chicken', 'Meat', 'kg', 12, 10],
  ['basmati', 'Basmati rice', 'Dry goods', 'kg', 38, 15],
  ['cream', 'Fresh cream', 'Dairy', 'L', 6, 7],
  ['tomato', 'Tomatoes', 'Produce', 'kg', 9, 8],
  ['atta', 'Tandoori atta', 'Dry goods', 'kg', 24, 12],
  ['mint', 'Fresh mint', 'Produce', 'bunch', 5, 6],
  ['mango', 'Mango pulp', 'Beverage', 'L', 14, 5],
];

await sql.transaction(
  inventory.map((item) =>
    sql.query(
      `INSERT INTO inventory (id, name, category, unit, quantity, reorder_at, updated_at)
       VALUES ($1, $2, $3, $4, $5, $6, $7)
       ON CONFLICT (id) DO NOTHING`,
      [...item, now],
    ),
  ),
);

console.log('Neon database schema is ready.');
